<?php
/**
 * @file
 * Add twisty dropbutton button.
 */

/**
 * Implements hook_theme().
 */
function ctools_twisty_dropbutton_theme() {
  return array(
    'ctools_twisty_dropbutton' => array(
      'variables' => array(
        'links' => array(),
      ),
    ),
  );
}

/**
 * Theme function for twisty dropdown.
 */
function theme_ctools_twisty_dropbutton($variables) {
  $links = $variables['links'];
  if (count($links) > 1) {
    ctools_add_js('dropbutton');
    ctools_add_css('dropbutton');
  }
  ctools_add_css('button');
  // Unique identifier buttons.
  static $twisty_id = 0;
  $twisty_id++;
  $output = '<div class="ctools-dropbutton ctools-button" id="ctools-button-' . $twisty_id . '">';
  $output .= '<div class="ctools-link">';
  $output .= '<a href="#" class="ctools-twisty ctools-text">' . t('open') . '</a>';
  $output .= '</div>';
  $output .= '<div class="ctools-content">';
  $output .= theme('item_list', array('items' => $links));
  $output .= '</div>';
  $output .= '</div>';

  return $output;
}
